import type { ImgHTMLAttributes } from 'react';

interface PictureProps extends ImgHTMLAttributes<HTMLImageElement> {
  /** Path to the JPEG/PNG fallback under /public (e.g. "/images/hero-abstract.jpg"). */
  src: string;
  /**
   * Skip the avif source. Use for above-the-fold/LCP images: Safari decodes
   * avif ~2× slower than webp, so the eager hero images serve webp instead —
   * below-the-fold imagery keeps avif's smaller bytes.
   */
  noAvif?: boolean;
}

/**
 * Drop-in replacement for `<img src="*.jpg">` that serves the avif/webp siblings
 * generated by `scripts/optimize-images.mjs` and falls back to the original
 * JPEG. The `<picture>` uses `display: contents` so it is completely transparent
 * to layout — the inner `<img>` keeps every class/attribute it had before, so
 * the rendering is pixel-identical, just lighter bytes.
 */
export const Picture = ({ src, alt = '', noAvif = false, ...img }: PictureProps) => {
  const base = src.replace(/\.(jpe?g|png)$/i, '');
  return (
    <picture style={{ display: 'contents' }}>
      {!noAvif && <source srcSet={`${base}.avif`} type="image/avif" />}
      <source srcSet={`${base}.webp`} type="image/webp" />
      <img src={src} alt={alt} decoding="async" {...img} />
    </picture>
  );
};
